# Generated by Django 3.0.9 on 2020-08-22 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('post_body', models.TextField()),
                ('post_pubdate', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 7, 22, 46, 204639, tzinfo=utc))),
                ('post_stat', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
        ),
    ]
