# Generated by Django 3.0.9 on 2020-08-22 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
